# Generated by Django 3.1.7 on 2021-06-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='people',
            field=models.IntegerField(),
        ),
    ]
